[application]
name = "radiant-fulcrum-gui"

[web.app]
title = "radiant-fulcrum-gui"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

# Fullstack configuration
[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[bundle]
identifier = "bio.seer.radiant-fulcrum-gui"
publisher = "Seer Inc."
icon = ["assets/radiant-logo.png"]
