[application]
name = "pythia-scry-gui"

[web.app]
title = "pythia-scry-gui"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

# Fullstack configuration
[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[bundle]
identifier = "bio.seer.pythia-scry-gui"
