name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            target: x86_64
#          - runner: ubuntu-24.04
#            target: aarch64
    steps:
      - run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        if: ${{ startsWith(matrix.platform.target, 'x86_64') }}
      - uses: Swatinem/rust-cache@v2
        if: ${{ startsWith(matrix.platform.target, 'x86_64') }}
      - name: Install Dioxus
        if: ${{ startsWith(matrix.platform.target, 'x86_64') }}
        run:
          cargo install dioxus-cli
      - name: Build with Dioxus
        if: ${{ startsWith(matrix.platform.target, 'x86_64') }}
        run:
          dx build --desktop
      - name: Run Rust unit tests
        if: ${{ startsWith(matrix.platform.target, 'x86_64') }}
        run:
          cargo test

  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-15-intel
            target: x86_64
          - runner: macos-15
            target: aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Dioxus
        run:
          cargo install dioxus-cli
      - name: Build with Dioxus
        run:
          dx build --desktop
      - name: Run Rust unit tests
        run:
          cargo test

  windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        if: ${{ startsWith(matrix.platform.target, 'x64') }}
      - uses: Swatinem/rust-cache@v2
        if: ${{ startsWith(matrix.platform.target, 'x64') }}
      - name: Install Dioxus
        if: ${{ startsWith(matrix.platform.target, 'x64') }}
        run:
          cargo install dioxus-cli
      - name: Build with Dioxus
        if: ${{ startsWith(matrix.platform.target, 'x64') }}
        run:
          dx build --desktop
      - name: Run Rust unit tests
        if: ${{ startsWith(matrix.platform.target, 'x64') }}
        run:
          cargo test

  web:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            target: wasm32
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Dioxus
        run:
          cargo install dioxus-cli
      - name: Build with Dioxus
        run:
          dx build --web --force-sequential true
